### ISSUE TITLE
Broken on `blightmud` master?

### ISSUE THREAD

**Issue by abesto** [cpu/blightspell#6]
```
> /add_plugin https://github.com/cpu/blightspell
[**] Downloading plugin: blightspell from https://github.com/cpu/blightspell
[**] Downloaded plugin: blightspell
[**] Getting the submodules for blightspell.
[**] Plugin retrieval succeeded.
> /load_plugin blightspell
[plugin] Loading: blightspell
[**] Loaded script: /home/abesto/.local/share/blightmud/plugins/blightspell/main.lua
[!!] [Lua] Script error:
[!!]    error converting Lua nil to table
```

`blightmud` built from source:

```
$ blightmud --version
blightmud v5.4.0 (v5.3.0-236-g6fa9338) 
```

The lack of a stack trace makes it hard to debug, hoping you can help!

**Comment by cpu** [comment]
Thanks for the report! I will take a look shortly

**Comment by cpu** [comment]
@abesto So far I'm not able to reproduce :thinking: 

```
Blightmud on  cpu-blightspell-6_impl [$?] is 📦 v5.4.0 via 🦀 v1.79.0-nightly via ❄️  impure (nix-shell-env)
❯ cargo build --release
<snipped>

Blightmud on  cpu-blightspell-6_impl [$?] is 📦 v5.4.0 via 🦀 v1.79.0-nightly via ❄️  impure (nix-shell-env)
❯ mv ~/.config/blightmud/ ~/.config/blightmud.old

Blightmud on  cpu-blightspell-6_impl [$?] is 📦 v5.4.0 via 🦀 v1.79.0-nightly via ❄️  impure (nix-shell-env)
❯ mv ~/.local/share/blightmud/ ~/.local/share/blightmud.old

❯ ./target/release/blightmud
```

```
┄Welcome

Blightmud 5.4.0 (v5.3.0-238-g6858349)

Created by: Linus Probert

Visit https://github.com/Blightmud/blightmud for latest information, bug reports and source code.

Type /connect <host> <port> to connect to a mud Type /help for more options

┄┄Changes

See /help changes to see what has changed in the latest major release.
> /add_plugin https://github.com/cpu/blightspell
[**] Downloading plugin: blightspell from https://github.com/cpu/blightspell
[**] Downloaded plugin: blightspell
[**] Getting the submodules for blightspell.
[**] Plugin retrieval succeeded.
> /load_plugin blightspell
[plugin] Loading: blightspell
[**] Loaded script: /home/daniel/.local/share/blightmud/plugins/blightspell/main.lua
[blightspell] spellchecking language: en
[blightspell] spellchecking enabled
```

Is there anything interesting in your `~/.local/share/blightmud/store/data.ron` file? Are you running this on Linux, macOS, or another platform?

**Comment by abesto** [comment]
Huh, then it must be something in my env.

```
cat ~/.local/share/blightmud/store/data.ron
{"mcp_settings":"{\"lambdamoo_connect_string\":\"\\\\*\\\\*\\\\* Connected \\\\*\\\\*\\\\*\",\"simpleedit_path\":\"/home/abesto/.local/share/blightmud/plugins/blightmud_mcpsimpleedit/\",\"debug_mcp\":false,\"stat_command\":\"stat\",\"simpleedit_timeout\":10800,\"edit_command\":\"code \\\"%FILE\\\"\"}"}
```

This is running on Arch under WSL (I like pain, what can I say)

Tried a clean build, just in case:

```
$ git clone https://github.com/Blightmud/Blightmud.git
Cloning into 'Blightmud'...
--- %< ---
Resolving deltas: 100% (5834/5834), done.
$ cd blightmud
$ cargo build --release
--- %< ---
    Finished `release` profile [optimized] target(s) in 2m 27s 
```

`load_plugin` then does give some useful output (I guess the build from AUR must have some optimizations enabled or something):

```
[!!] [Lua] Script error:
[!!]    runtime error: .../.local/share/blightmud/plugins/blightspell/src/init.lua:8: attempt to index a nil value (global 'blightspell_settings')
[!!]    stack traceback:
[!!]            [C]: in metamethod 'index'
[!!]            .../.local/share/blightmud/plugins/blightspell/src/init.lua:8: in function 'blightspell_init'
[!!]            .../.local/share/blightmud/plugins/blightspell/src/init.lua:30: in main chunk
[!!]            [C]: in function 'require'
[!!]            [string "/home/abesto/.local/share/blightmud/plugins/b..."]:21: in main chunk
```

**Comment by abesto** [comment]
At first glance: `blighspell` might assume that if there's a config file, then it must also contain a `blightspell` key?

**Comment by abesto** [comment]
Hm, this should be fine.

```
if store.disk_read(plugin_name) == nil then
  blightspell_defaults_init()
end
```

**Comment by cpu** [comment]
> This is running on Arch under WSL (I like pain, what can I say)

:laughing: 

> load_plugin then does give some useful output (I guess the build from AUR must have some optimizations enabled or something):

That is helpful, thank you!

> At first glance: blighspell might assume that if there's a config file, then it must also contain a blightspell key?

It does seem related to the settings init, but I thought the defaults would be written if the blightspell key weren't present:

https://github.com/cpu/blightspell/blob/b80cbe32f40747d30c999bbbedbe42f70ea89b02/src/settings.lua#L138-L141

Edit: looks like we both arrived at that conclusion :-)

**Comment by abesto** [comment]
Gotta check on something else, but after poking a bit, it seems like `settings.lua` is not loaded at all for me? Is that possible?

**Comment by cpu** [comment]
>  it seems like settings.lua is not loaded at all for me? Is that possible?

It should be loaded first in `main.lua`:

https://github.com/cpu/blightspell/blob/b80cbe32f40747d30c999bbbedbe42f70ea89b02/main.lua#L17-L21

**Comment by abesto** [comment]
> It should be loaded first in main.lua

Right, then I must be holding it wrong. I'll try again.

**Comment by cpu** [comment]
I think I might have been able to reproduce by first installing the [blightmud_mcp](https://github.com/lisdude/blightmud_mcp) plugin. 

Let me see if I can puzzle out what's going on here. IIRC the way I'm handling settings was heavily inspired by Lisdude's work, it's possible there's an unplanned interaction between the two.

**Comment by abesto** [comment]
This is weird as hell. I added debug `blight.output` calls before the `src/settings` require, after it, and inside the file at the top. Have output before, have output after, but don't have output *inside*.

**Comment by cpu** [comment]
I wonder if it's as simple as using the same `settings.lua` name and having a conflict with the `require` path resolution:
https://github.com/lisdude/blightmud_mcp/blob/9661b75abbe890487c8e0daca1dcfb131c3658ca/main.lua#L9

That seems like it would match your observation of the missing output from Blightspell's `src/settings` - my theory is that `require` is loading the blightmud_mcp `settings.lua` instead.

**Comment by abesto** [comment]
Yeah I can imagine `blightmud` is running a single Lua interpreter that optimizes out duplicate loads of "the same module"

**Comment by cpu** [comment]
Renaming `settings.lua` and the `require` in Blightspell did the trick. 

I'll open a PR in a moment that prefixes all of the `require`'d files to avoid this. This kind of thing is one of the reasons I don't particluarly _love_ Lua :laughing:

**Comment by abesto** [comment]
Right, this seems like a problem with how Blightmud executes Lua then. The interpreter thinks this all plugins are in one shared source tree :( Want me to file the issue on Blightmud?

Thank you for putting in a workaround! :D

**Comment by abesto** [comment]
Confirm I now have working spell checking after `/update_plugins`!

**Comment by cpu** [comment]
> Confirm I now have working spell checking after /update_plugins!

Awesome. Glad to hear it. Thanks for your help getting to the bottom of this. It was pretty mysterious.

>  The interpreter thinks this all plugins are in one shared source tree :( Want me to file the issue on Blightmud?

Sure, it might be helpful to at least communicate the problem exists. I suspect other plugin authors will bump into this sooner or later. Perhaps there's a fix that could be landed on that side (though I'm unlikely to have the time to pursue it myself).
